### ISSUE TITLE
Help option issues

### ISSUE THREAD

**Issue by hwerglmir** [jcowgar/xojo-option-parser#7]
Adding a option "h" as shortkey throws the wrong Exception. You check for the "?" not for the "h".
In the Constructor of OptionParser you add the help option with "h".

**Comment by jcowgar** [comment]
That code is a bit tricky. In the Constructor we add the "h" option but in AddOption we test specifically for the "Alias" of "?" because OptionParser does not yet support aliasing. The "h" option will already be tested for because prior to the "?" check, it looks at existing options to see if there is a clash.

In the "Parse" method, if we see a "-?" then it rewrites it to "-h" which was added in the Constructor.

Does that make sense or are you pointing out a different error?

**Comment by hwerglmir** [comment]
Ah ok. That makes sense. 
Thanks. 

Great lib. 

Daniel

**Comment by jcowgar** [comment]
Thanks! We will work on your other feature request, that is a good idea.
